FROM node:20-alpine
WORKDIR /app

# argon2 needs build tools for native bindings
RUN apk add --no-cache python3 make g++ libc6-compat

COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4000
CMD ["npx", "tsx", "watch", "src/index.ts"]
